# Generated by Django 5.2.5 on 2025-09-07 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('credit_rating', models.CharField(choices=[('AAA', 'AAA - Excellent'), ('AA', 'AA - Very Good'), ('A', 'A - Good'), ('BBB', 'BBB - Fair'), ('BB', 'BB - Marginal'), ('B', 'B - Poor'), ('B+', 'B+ - Poor Plus'), ('CCC', 'CCC - Very Poor'), ('CC', 'CC - Extremely Poor'), ('C', 'C - Default Imminent'), ('D', 'D - In Default')], max_length=10)),
                ('application_date', models.DateField()),
                ('settlement_date', models.DateField()),
                ('evaluation_date', models.DateField()),
                ('expiration_date', models.DateField()),
                ('report_status', models.CharField(choices=[('effectiveness', 'Effectiveness'), ('processing', 'Processing'), ('expiration', 'Expiration'), ('cancelled', 'Cancelled')], default='processing', max_length=20)),
                ('submission_office', models.CharField(default='View the main building', max_length=200)),
                ('report_file', models.FileField(blank=True, null=True, upload_to='credit_reports/')),
                ('annual_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('assets_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('liabilities', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('rating_rationale', models.TextField(blank=True, null=True)),
                ('key_strengths', models.TextField(blank=True, null=True)),
                ('key_concerns', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Credit Rating',
                'verbose_name_plural': 'Credit Ratings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DashboardActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('login', 'User Login'), ('logout', 'User Logout'), ('view_dashboard', 'Viewed Dashboard'), ('view_report', 'Viewed Report'), ('download_report', 'Downloaded Report'), ('print_invoice', 'Printed Invoice'), ('update_profile', 'Updated Profile'), ('submit_application', 'Submitted Application')], max_length=20)),
                ('description', models.CharField(max_length=200)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('related_credit_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='userdashboard.creditrating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Activity',
                'verbose_name_plural': 'Dashboard Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_emails', models.BooleanField(default=False)),
                ('default_dashboard_view', models.CharField(choices=[('overview', 'Overview'), ('reports', 'My Reports'), ('history', 'Application History')], default='overview', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
        migrations.CreateModel(
            name='ReportAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.CharField(choices=[('view', 'View Only'), ('download', 'Download Allowed'), ('print', 'Print Allowed'), ('share', 'Share Allowed')], default='view', max_length=20)),
                ('accessed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('credit_rating', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userdashboard.creditrating')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-accessed_at'],
                'unique_together': {('user', 'credit_rating')},
            },
        ),
    ]
